<script lang="ts">
	import Button from '$lib/components/atoms/Button.svelte'
</script>

<div class="flex h-full w-full items-center justify-center">
	<h1 class="text-4xl">A Svelte Template</h1>
</div>
<div class="leading-tight">
	<div class="text-9xl">text-9xl</div>
	<div class="text-8xl">text-8xl</div>
	<div class="text-7xl">text-7xl</div>
	<div class="text-6xl">text-6xl</div>
	<div class="text-5xl">text-5xl</div>
	<div class="text-4xl">text-4xl</div>
	<div class="text-3xl">text-3xl</div>
	<div class="text-2xl">text-2xl</div>
	<div class="text-xl">text-xl</div>
	<div class="text-lg">text-lg</div>
	<div class="text-base">text-base</div>
	<div class="text-sm">text-sm</div>
	<div class="text-xs">text-xs</div>
</div>

<div class="flex flex-col">
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-grey-0" />
		<div class="flex-auto bg-grey-1" />
		<div class="flex-auto bg-grey-2" />
		<div class="flex-auto bg-grey-3" />
		<div class="flex-auto bg-grey-4" />
		<div class="flex-auto bg-grey-5" />
		<div class="flex-auto bg-grey-6" />
		<div class="flex-auto bg-grey-7" />
		<div class="flex-auto bg-grey-8" />
		<div class="flex-auto bg-grey-9" />
		<div class="flex-auto bg-grey-10" />
		<div class="flex-auto bg-grey-11" />
		<div class="flex-auto bg-grey-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-red-0" />
		<div class="flex-auto bg-red-1" />
		<div class="flex-auto bg-red-2" />
		<div class="flex-auto bg-red-3" />
		<div class="flex-auto bg-red-4" />
		<div class="flex-auto bg-red-5" />
		<div class="flex-auto bg-red-6" />
		<div class="flex-auto bg-red-7" />
		<div class="flex-auto bg-red-8" />
		<div class="flex-auto bg-red-9" />
		<div class="flex-auto bg-red-10" />
		<div class="flex-auto bg-red-11" />
		<div class="flex-auto bg-red-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-pink-0" />
		<div class="flex-auto bg-pink-1" />
		<div class="flex-auto bg-pink-2" />
		<div class="flex-auto bg-pink-3" />
		<div class="flex-auto bg-pink-4" />
		<div class="flex-auto bg-pink-5" />
		<div class="flex-auto bg-pink-6" />
		<div class="flex-auto bg-pink-7" />
		<div class="flex-auto bg-pink-8" />
		<div class="flex-auto bg-pink-9" />
		<div class="flex-auto bg-pink-10" />
		<div class="flex-auto bg-pink-11" />
		<div class="flex-auto bg-pink-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-purple-0" />
		<div class="flex-auto bg-purple-1" />
		<div class="flex-auto bg-purple-2" />
		<div class="flex-auto bg-purple-3" />
		<div class="flex-auto bg-purple-4" />
		<div class="flex-auto bg-purple-5" />
		<div class="flex-auto bg-purple-6" />
		<div class="flex-auto bg-purple-7" />
		<div class="flex-auto bg-purple-8" />
		<div class="flex-auto bg-purple-9" />
		<div class="flex-auto bg-purple-10" />
		<div class="flex-auto bg-purple-11" />
		<div class="flex-auto bg-purple-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-violet-0" />
		<div class="flex-auto bg-violet-1" />
		<div class="flex-auto bg-violet-2" />
		<div class="flex-auto bg-violet-3" />
		<div class="flex-auto bg-violet-4" />
		<div class="flex-auto bg-violet-5" />
		<div class="flex-auto bg-violet-6" />
		<div class="flex-auto bg-violet-7" />
		<div class="flex-auto bg-violet-8" />
		<div class="flex-auto bg-violet-9" />
		<div class="flex-auto bg-violet-10" />
		<div class="flex-auto bg-violet-11" />
		<div class="flex-auto bg-violet-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-indigo-0" />
		<div class="flex-auto bg-indigo-1" />
		<div class="flex-auto bg-indigo-2" />
		<div class="flex-auto bg-indigo-3" />
		<div class="flex-auto bg-indigo-4" />
		<div class="flex-auto bg-indigo-5" />
		<div class="flex-auto bg-indigo-6" />
		<div class="flex-auto bg-indigo-7" />
		<div class="flex-auto bg-indigo-8" />
		<div class="flex-auto bg-indigo-9" />
		<div class="flex-auto bg-indigo-10" />
		<div class="flex-auto bg-indigo-11" />
		<div class="flex-auto bg-indigo-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-blue-0" />
		<div class="flex-auto bg-blue-1" />
		<div class="flex-auto bg-blue-2" />
		<div class="flex-auto bg-blue-3" />
		<div class="flex-auto bg-blue-4" />
		<div class="flex-auto bg-blue-5" />
		<div class="flex-auto bg-blue-6" />
		<div class="flex-auto bg-blue-7" />
		<div class="flex-auto bg-blue-8" />
		<div class="flex-auto bg-blue-9" />
		<div class="flex-auto bg-blue-10" />
		<div class="flex-auto bg-blue-11" />
		<div class="flex-auto bg-blue-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-cyan-0" />
		<div class="flex-auto bg-cyan-1" />
		<div class="flex-auto bg-cyan-2" />
		<div class="flex-auto bg-cyan-3" />
		<div class="flex-auto bg-cyan-4" />
		<div class="flex-auto bg-cyan-5" />
		<div class="flex-auto bg-cyan-6" />
		<div class="flex-auto bg-cyan-7" />
		<div class="flex-auto bg-cyan-8" />
		<div class="flex-auto bg-cyan-9" />
		<div class="flex-auto bg-cyan-10" />
		<div class="flex-auto bg-cyan-11" />
		<div class="flex-auto bg-cyan-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-teal-0" />
		<div class="flex-auto bg-teal-1" />
		<div class="flex-auto bg-teal-2" />
		<div class="flex-auto bg-teal-3" />
		<div class="flex-auto bg-teal-4" />
		<div class="flex-auto bg-teal-5" />
		<div class="flex-auto bg-teal-6" />
		<div class="flex-auto bg-teal-7" />
		<div class="flex-auto bg-teal-8" />
		<div class="flex-auto bg-teal-9" />
		<div class="flex-auto bg-teal-10" />
		<div class="flex-auto bg-teal-11" />
		<div class="flex-auto bg-teal-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-green-0" />
		<div class="flex-auto bg-green-1" />
		<div class="flex-auto bg-green-2" />
		<div class="flex-auto bg-green-3" />
		<div class="flex-auto bg-green-4" />
		<div class="flex-auto bg-green-5" />
		<div class="flex-auto bg-green-6" />
		<div class="flex-auto bg-green-7" />
		<div class="flex-auto bg-green-8" />
		<div class="flex-auto bg-green-9" />
		<div class="flex-auto bg-green-10" />
		<div class="flex-auto bg-green-11" />
		<div class="flex-auto bg-green-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-lime-0" />
		<div class="flex-auto bg-lime-1" />
		<div class="flex-auto bg-lime-2" />
		<div class="flex-auto bg-lime-3" />
		<div class="flex-auto bg-lime-4" />
		<div class="flex-auto bg-lime-5" />
		<div class="flex-auto bg-lime-6" />
		<div class="flex-auto bg-lime-7" />
		<div class="flex-auto bg-lime-8" />
		<div class="flex-auto bg-lime-9" />
		<div class="flex-auto bg-lime-10" />
		<div class="flex-auto bg-lime-11" />
		<div class="flex-auto bg-lime-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-yellow-0" />
		<div class="flex-auto bg-yellow-1" />
		<div class="flex-auto bg-yellow-2" />
		<div class="flex-auto bg-yellow-3" />
		<div class="flex-auto bg-yellow-4" />
		<div class="flex-auto bg-yellow-5" />
		<div class="flex-auto bg-yellow-6" />
		<div class="flex-auto bg-yellow-7" />
		<div class="flex-auto bg-yellow-8" />
		<div class="flex-auto bg-yellow-9" />
		<div class="flex-auto bg-yellow-10" />
		<div class="flex-auto bg-yellow-11" />
		<div class="flex-auto bg-yellow-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-orange-0" />
		<div class="flex-auto bg-orange-1" />
		<div class="flex-auto bg-orange-2" />
		<div class="flex-auto bg-orange-3" />
		<div class="flex-auto bg-orange-4" />
		<div class="flex-auto bg-orange-5" />
		<div class="flex-auto bg-orange-6" />
		<div class="flex-auto bg-orange-7" />
		<div class="flex-auto bg-orange-8" />
		<div class="flex-auto bg-orange-9" />
		<div class="flex-auto bg-orange-10" />
		<div class="flex-auto bg-orange-11" />
		<div class="flex-auto bg-orange-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-choco-0" />
		<div class="flex-auto bg-choco-1" />
		<div class="flex-auto bg-choco-2" />
		<div class="flex-auto bg-choco-3" />
		<div class="flex-auto bg-choco-4" />
		<div class="flex-auto bg-choco-5" />
		<div class="flex-auto bg-choco-6" />
		<div class="flex-auto bg-choco-7" />
		<div class="flex-auto bg-choco-8" />
		<div class="flex-auto bg-choco-9" />
		<div class="flex-auto bg-choco-10" />
		<div class="flex-auto bg-choco-11" />
		<div class="flex-auto bg-choco-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-brown-0" />
		<div class="flex-auto bg-brown-1" />
		<div class="flex-auto bg-brown-2" />
		<div class="flex-auto bg-brown-3" />
		<div class="flex-auto bg-brown-4" />
		<div class="flex-auto bg-brown-5" />
		<div class="flex-auto bg-brown-6" />
		<div class="flex-auto bg-brown-7" />
		<div class="flex-auto bg-brown-8" />
		<div class="flex-auto bg-brown-9" />
		<div class="flex-auto bg-brown-10" />
		<div class="flex-auto bg-brown-11" />
		<div class="flex-auto bg-brown-12" />
	</div>
	<div class="flex h-24 w-full">
		<div class="flex-auto bg-sand-0" />
		<div class="flex-auto bg-sand-1" />
		<div class="flex-auto bg-sand-2" />
		<div class="flex-auto bg-sand-3" />
		<div class="flex-auto bg-sand-4" />
		<div class="flex-auto bg-sand-5" />
		<div class="flex-auto bg-sand-6" />
		<div class="flex-auto bg-sand-7" />
		<div class="flex-auto bg-sand-8" />
		<div class="flex-auto bg-sand-9" />
		<div class="flex-auto bg-sand-10" />
		<div class="flex-auto bg-sand-11" />
		<div class="flex-auto bg-sand-12" />
	</div>
</div>
